export const items = [
  {
    title: 'Astro',
    avatar: 'https://avatars.githubusercontent.com/u/44914786?s=48&v=4',
    description: '一个现代化的静态站点生成框架',
    link: 'https://github.com/withastro/astro',
    tags: ['框架'],
  },
  {
    title: '天影大侠的小站',
    avatar: 'https://weavatar.com/avatar/7388ea4765a319d5f83fea61c3236384?s=1000',
    description: 'The Blog of SkyShadowHero!',
    link: 'https://blog.skyshadow.fun/',
    rss: 'https://blog.skyshadow.fun/rss.xml',
    tags: ['友链'],
  },
  {
    title: '伊卡的记事本',
    avatar: 'https://ikamusume7.org/avatar.webp',
    description: '又菜又爱学',
    link: 'https://ikamusume7.org',
    rss: 'https://ikamusume7.org/rss.xml',
    tags: ['友链'],
  },
  {
    title: 'Mayx的博客',
    avatar: 'https://avatars0.githubusercontent.com/u/17966333',
    description: 'Mayx’s Home Page',
    link: 'https://mayx.gitlab.io/',
    rss: 'https://mayx.gitlab.io/atom.xml',
    tags: ['友链'],
  },
  {
    title: '小岚的杂物间',
    avatar: 'https://avatar.guirlan.de/avatar/172530293dcfb25d871a72ccb39b21c2/256',
    description: '这里储存着各种稀奇古怪事物~',
    link: 'https://www.guirlan.de',
    rss: 'https://www.guirlan.de/atom.xml',
    tags: ['友链'],
  },
  {
    title: 'LineXic书屋',
    avatar: 'https://linexic.top/avatar.webp',
    description: '难离难舍，想抱紧些',
    link: 'https://www.linexic.top/',
    rss: 'https://www.linexic.top/rss.xml',
    tags: ['友链'],
  },
  {
    title: '独元殇',
    avatar: 'https://img1.ccgxk.com/ccgxk-oss/2025/05/202505191037317NTuR1.jpg',
    description: '月光刚好，你在仰望，我们一起仰望',
    link: 'https://www.ccgxk.com',
    rss: 'https://www.ccgxk.com/rss.php',
    tags: ['友链'],
  },
  {
    title: '流月小站',
    avatar: 'https://cdn.liuyue.net/assets/img/avatar.jpg',
    description: '且听风吟，静待花开',
    link: 'https://blog.flowmoon.cn/',
    rss: 'https://blog.flowmoon.cn/rss.xml',
    tags: ['友链'],
  },
  {
    title: 'Pinpe 的云端',
    avatar: 'https://pinpe.top/head.jpg',
    description: '一个属于自己的云朵。',
    link: 'https://pinpe.top/',
    rss: 'https://pinpe.top/rss.xml',
    tags: ['友链'],
  },
  {
    title: "wuxian's web",
    avatar: '',
    description: '你喜欢吃青椒吗？',
    link: 'https://alxian.cn/',
    tags: ['友链'],
  },
  {
    title: '酥米的小站',
    avatar:
      'https://cdn.jsdmirror.com/gh/huang233893/blog-image-bed/top/huang233893/imgs/blog/userfb6a1018b84ce485.jpg',
    description: '有朝一日，寻见梦中人✨',
    link: 'https://www.sumi233.top/',
    rss: 'https://www.sumi233.top/rss.xml',
    tags: ['友链'],
  },
  {
    title: 'Evilrabbit Blog',
    avatar: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
    description: '爱 Coding 爱生活',
    link: 'https://blog.yujiay.wang/',
    rss: 'https://blog.yujiay.wang/atom.xml',
    tags: ['友链'],
  },
  {
    title: '两个笨笨',
    avatar: 'https://pan.mkirin.top/f/9Bt9/icon.png',
    description: '两个笨笨的blog',
    link: 'https://mkirin.top',
    tags: ['友链'],
  },
  {
    title: '吐司气泡',
    avatar: 'https://blog.toastbubble.top/avatar.webp',
    description: '追求源于热爱',
    link: 'https://blog.toastbubble.top/',
    tags: ['友链'],
  },
  {
    title: '清羽飞扬',
    avatar: 'https://blog.liushen.fun/info/avatar.ico',
    description: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
    link: 'https://blog.liushen.fun/',
    rss: 'https://blog.liushen.fun/atom.xml',
    tags: ['友链'],
  }
]
